/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author ABHISHEK PRAKASH
 */
public class CreatePersonJPanel extends javax.swing.JPanel {

    private final PersonDirectory personDirectory;

    /**
     * Creates new form CreatePersonJPanel
     */
    public CreatePersonJPanel(PersonDirectory personDirectory) {
        initComponents();
        this.personDirectory = personDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lblHZipCode = new javax.swing.JLabel();
        txtHZipCode = new javax.swing.JTextField();
        lblWCity = new javax.swing.JLabel();
        lblWStrAddress = new javax.swing.JLabel();
        txtWCity = new javax.swing.JTextField();
        txtWStrAddress = new javax.swing.JTextField();
        lblWState = new javax.swing.JLabel();
        lblWUnitNumber = new javax.swing.JLabel();
        txtWState = new javax.swing.JTextField();
        txtWUnitNumber = new javax.swing.JTextField();
        txtHStrAddress = new javax.swing.JTextField();
        lblHState = new javax.swing.JLabel();
        lblHUnitNumber = new javax.swing.JLabel();
        txtHState = new javax.swing.JTextField();
        txtHUnitNumber = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblHomeAddress = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblHCity = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblHStrAddress = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        txtHCity = new javax.swing.JTextField();
        lblSSN = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        txtSSN = new javax.swing.JTextField();
        lblWZipCode = new javax.swing.JLabel();
        lblLicenseNumber = new javax.swing.JLabel();
        txtWZipCode = new javax.swing.JTextField();
        txtLicenseNumber = new javax.swing.JTextField();
        lblWorkAddress = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(255, 255, 255));

        lblHZipCode.setForeground(new java.awt.Color(255, 255, 255));
        lblHZipCode.setText("Zip Code");

        txtHZipCode.setBackground(new java.awt.Color(204, 204, 204));
        txtHZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHZipCodeActionPerformed(evt);
            }
        });

        lblWCity.setForeground(new java.awt.Color(255, 255, 255));
        lblWCity.setText("City");

        lblWStrAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblWStrAddress.setText("Street Address");

        txtWCity.setBackground(new java.awt.Color(204, 204, 204));
        txtWCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWCityActionPerformed(evt);
            }
        });

        txtWStrAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtWStrAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWStrAddressActionPerformed(evt);
            }
        });

        lblWState.setForeground(new java.awt.Color(255, 255, 255));
        lblWState.setText("State");

        lblWUnitNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblWUnitNumber.setText("Unit Number");

        txtWState.setBackground(new java.awt.Color(204, 204, 204));
        txtWState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWStateActionPerformed(evt);
            }
        });

        txtWUnitNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtWUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWUnitNumberActionPerformed(evt);
            }
        });

        txtHStrAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtHStrAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHStrAddressActionPerformed(evt);
            }
        });

        lblHState.setForeground(new java.awt.Color(255, 255, 255));
        lblHState.setText("State");

        lblHUnitNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblHUnitNumber.setText("Unit Number");

        txtHState.setBackground(new java.awt.Color(204, 204, 204));
        txtHState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHStateActionPerformed(evt);
            }
        });

        txtHUnitNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtHUnitNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHUnitNumberActionPerformed(evt);
            }
        });

        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name");

        lblHomeAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblHomeAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblHomeAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeAddress.setText("Home Address");

        txtFirstName.setBackground(new java.awt.Color(204, 204, 204));
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        lblHCity.setForeground(new java.awt.Color(255, 255, 255));
        lblHCity.setText("City");

        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name");

        lblHStrAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblHStrAddress.setText("Street Address");

        txtLastName.setBackground(new java.awt.Color(204, 204, 204));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        txtHCity.setBackground(new java.awt.Color(204, 204, 204));
        txtHCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHCityActionPerformed(evt);
            }
        });

        lblSSN.setForeground(new java.awt.Color(255, 255, 255));
        lblSSN.setText("Social Security Number");

        btnCreateAccount.setBackground(new java.awt.Color(51, 255, 0));
        btnCreateAccount.setText("Create");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        txtSSN.setBackground(new java.awt.Color(204, 204, 204));
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblWZipCode.setForeground(new java.awt.Color(255, 255, 255));
        lblWZipCode.setText("Zip Code");

        lblLicenseNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblLicenseNumber.setText("License Number");

        txtWZipCode.setBackground(new java.awt.Color(204, 204, 204));
        txtWZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWZipCodeActionPerformed(evt);
            }
        });

        txtLicenseNumber.setBackground(new java.awt.Color(204, 204, 204));
        txtLicenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicenseNumberActionPerformed(evt);
            }
        });

        lblWorkAddress.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWorkAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblWorkAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWorkAddress.setText("Work Address");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblHCity, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(165, 165, 165))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtHCity)
                                            .addGap(93, 93, 93)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblHState, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtHState)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHStrAddress)
                                        .addComponent(lblHStrAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(93, 93, 93)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtHUnitNumber)
                                        .addComponent(lblHUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtWZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtFirstName)
                                                .addComponent(lblFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(93, 93, 93)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLastName)
                                                .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtSSN, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(93, 93, 93)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtLicenseNumber)
                                                .addComponent(lblLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(lblWorkAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtWStrAddress)
                                                .addComponent(lblWStrAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                .addComponent(lblWCity, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                                .addComponent(txtWCity))
                                            .addGap(93, 93, 93)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblWState, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtWUnitNumber)
                                                    .addComponent(lblWUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(lblWZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblHomeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(425, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFirstName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLicenseNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSSN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblWorkAddress)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWUnitNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblWStrAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWStrAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWCity)
                    .addComponent(lblWState))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWZipCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblHomeAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHUnitNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHUnitNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHStrAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHStrAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblHCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHState)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHZipCode)
                    .addComponent(btnCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHZipCodeActionPerformed

    private void txtWCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWCityActionPerformed

    private void txtWStrAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWStrAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWStrAddressActionPerformed

    private void txtWStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWStateActionPerformed

    private void txtWUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWUnitNumberActionPerformed

    private void txtHStrAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHStrAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHStrAddressActionPerformed

    private void txtHStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHStateActionPerformed

    private void txtHUnitNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHUnitNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHUnitNumberActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtHCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHCityActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        String ssn = txtSSN.getText();
        String license = txtLicenseNumber.getText();

        String workSteetAddress = txtWStrAddress.getText();
        String workUnitNumber = txtWUnitNumber.getText();
        String workCity = txtWCity.getText();
        String workState = txtWState.getText();
        String workZipCode = txtWZipCode.getText();

        String homeSteetAddress = txtHStrAddress.getText();
        String homeUnitNumber = txtHUnitNumber.getText();
        String homeCity = txtHCity.getText();
        String homeState = txtHState.getText();
        String homeZipCode = txtHZipCode.getText();

        Person person = personDirectory.addPerson();
        person.setFirstName(firstName);
        person.setLastName(lastName);
        person.setSsn(ssn);
        person.setLicense(license);

        person.setWorkAddress(workSteetAddress, workUnitNumber, workCity, workState, workZipCode);
        person.setHomeAddress(homeSteetAddress, homeUnitNumber, homeCity, homeState, homeZipCode);

        JOptionPane.showMessageDialog(null, "Person iforatio saved sccesflly");
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtWZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWZipCodeActionPerformed

    private void txtLicenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicenseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicenseNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHCity;
    private javax.swing.JLabel lblHState;
    private javax.swing.JLabel lblHStrAddress;
    private javax.swing.JLabel lblHUnitNumber;
    private javax.swing.JLabel lblHZipCode;
    private javax.swing.JLabel lblHomeAddress;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLicenseNumber;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblWCity;
    private javax.swing.JLabel lblWState;
    private javax.swing.JLabel lblWStrAddress;
    private javax.swing.JLabel lblWUnitNumber;
    private javax.swing.JLabel lblWZipCode;
    private javax.swing.JLabel lblWorkAddress;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHCity;
    private javax.swing.JTextField txtHState;
    private javax.swing.JTextField txtHStrAddress;
    private javax.swing.JTextField txtHUnitNumber;
    private javax.swing.JTextField txtHZipCode;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLicenseNumber;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtWCity;
    private javax.swing.JTextField txtWState;
    private javax.swing.JTextField txtWStrAddress;
    private javax.swing.JTextField txtWUnitNumber;
    private javax.swing.JTextField txtWZipCode;
    // End of variables declaration//GEN-END:variables
}
